#cloud-config
ssh_authorized_keys:
  - "${user_pubkey}"
write_files:
  - path: /etc/hosts
    content: ${hosts_context}
    permissions: 0644
    owner: root
    encoding: b64
  - path: /etc/vpm/config.yaml
    permissions: 0644
    owner: root
    encoding: b64
    content: ${vp_manager_context}
  - path: "/etc/systemd/chronyd.conf"
    permissions: 0420
    owner: root
    content: |
      pool pool.ntp.org iburst
      driftfile /var/lib/chrony/drift
      makestep 0.1 3
      rtcsync
